replicaCount: 2

image:
  repository: sigmawoman/api_gateway
  pullPolicy: IfNotPresent
  tag: "31586a60d34c8fd18b365e1a1e7ca0316d4f0ee2"

service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000

env:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/music_db"
  REDIS_URL: "redis://redis:6379"
  USER_GRPC_URL: "user-service:50051"
  PLAYLIST_GRPC_URL: "playlist-service:50052"
  CATALOG_GRPC_URL: "catalog-service:50053"
  SECRET_KEY: "K9mP2qR5vT8wY3nB6cF1jH4sL0zA7xX"

ingress:
  enabled: true
  className: "nginx"
  host: music.local
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "10"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"