postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: music_db
  primary:
    persistence:
      size: 1Gi

redis:
  enabled: true
  auth:
    enabled: false

kafka:
  enabled: true
  zookeeper:
    enabled: true
  listeners:
    client:
      protocol: PLAINTEXT
  # Добавляем переменные окружения, которые строго требует образ Confluent Kafka
  env:
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "PLAINTEXT://kafka:9092"
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: "1"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "zookeeper:2181"

mongodb:
  enabled: true
  auth:
    enabled: false
  persistence:
    size: 1Gi