syntax = "proto3";

package catalog;

service CatalogService {
    rpc GetTrack (GetTrackRequest) returns (GetTrackResponse);
    rpc SearchTracks (SearchTracksRequest) returns (SearchTracksResponse);
}

message GetTrackRequest {
    string track_id = 1;
}

message Track {
    string id = 1;
    string title = 2;
    string artist = 3;
    string album = 4;
    string genre = 5;
    string cover = 6;      // URL обложки альбома
    string preview = 7;    // URL 30-секундного MP3 превью
}

message GetTrackResponse {
    Track track = 1;
    bool found = 2;
}

message SearchTracksRequest {
    string query = 1;
    int32 limit = 2;
}

message SearchTracksResponse {
    repeated Track tracks = 1;
}