# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from catalog_service import catalog_pb2 as catalog__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in catalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatalogServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTrack = channel.unary_unary(
                '/catalog.CatalogService/GetTrack',
                request_serializer=catalog__pb2.GetTrackRequest.SerializeToString,
                response_deserializer=catalog__pb2.GetTrackResponse.FromString,
                _registered_method=True)
        self.SearchTracks = channel.unary_unary(
                '/catalog.CatalogService/SearchTracks',
                request_serializer=catalog__pb2.SearchTracksRequest.SerializeToString,
                response_deserializer=catalog__pb2.SearchTracksResponse.FromString,
                _registered_method=True)


class CatalogServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchTracks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrack,
                    request_deserializer=catalog__pb2.GetTrackRequest.FromString,
                    response_serializer=catalog__pb2.GetTrackResponse.SerializeToString,
            ),
            'SearchTracks': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchTracks,
                    request_deserializer=catalog__pb2.SearchTracksRequest.FromString,
                    response_serializer=catalog__pb2.SearchTracksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'catalog.CatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('catalog.CatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.CatalogService/GetTrack',
            catalog__pb2.GetTrackRequest.SerializeToString,
            catalog__pb2.GetTrackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchTracks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.CatalogService/SearchTracks',
            catalog__pb2.SearchTracksRequest.SerializeToString,
            catalog__pb2.SearchTracksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
