replicaCount: 2

image:
  repository: sigmawoman/playlist_service
  pullPolicy: IfNotPresent
  tag: "31586a60d34c8fd18b365e1a1e7ca0316d4f0ee2"

service:
  type: ClusterIP
  port: 50052

env:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/music_db"
  REDIS_URL: "redis://redis:6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_TOPIC: "playlist_events"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"