replicaCount: 2

image:
  repository: sigmawoman/playlist_service
  pullPolicy: Always
  tag: "bc7bfcf9fd10b826bb1e2f8b86ccda701cd7c85f"

service:
  type: ClusterIP
  port: 50052

env:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/music_db"
  REDIS_URL: "redis://redis:6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_TOPIC: "playlist_events"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"