replicaCount: 2

image:
  repository: sigmawoman/user_service
  pullPolicy: Always
  tag: "bc7bfcf9fd10b826bb1e2f8b86ccda701cd7c85f"

service:
  type: ClusterIP
  port: 50051

env:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/music_db"
  REDIS_URL: "redis://redis:6379"
  SECRET_KEY: "K9mP2qR5vT8wY3nB6cF1jH4sL0zA7xX"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"