replicaCount: 2

image:
  repository: sigmawoman/catalog_service
  pullPolicy: Always
  tag: "87dc9447df324719128b3767a92f2caa1f8235a8"

service:
  type: ClusterIP
  port: 50053

env:
  JAMENDO_CLIENT_ID: "b5ff5594"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"