replicaCount: 2

image:
  repository: sigmawoman/catalog_service
  pullPolicy: Always
  tag: "e432c377aec2d707aca4c2cec51cb3973a893148"

service:
  type: ClusterIP
  port: 50053

env:
  JAMENDO_CLIENT_ID: "b5ff5594"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"