replicaCount: 2

image:
  repository: sigmawoman/catalog_service
  pullPolicy: IfNotPresent
  tag: "ad514cabaf7a018887a8cb253e7dd38042385f54"

service:
  type: ClusterIP
  port: 50053

env:
  JAMENDO_CLIENT_ID: "b5ff5594"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"